version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    network_mode:
      host
    environment:
      - MONGO_INITDB_DATABASE=mydatabase
      - MONGO_INITDB_ROOT_USERNAME=myusername
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
      - MONGO_DB_USERNAME=myusername
      - MONGO_DB_PASSWORD=mypassword
#  app:
#    build: .
#    ports:
#      - 8080:8080
#    depends_on:
#      - mongodb
volumes:
  mongodb_data: